config/routes.rb
Rails.application.routes.draw do

  get 'session/new' => 'sessions#new', as: :sign_in
  post 'session/new' => 'sessions#create'
  delete 'session' => 'sessions#delete', as: :sign_out

  get 'users/new' => 'users#new', as: :new_user
  post 'users' => 'users#create', as: :users
  get 'users/:confirm_token/verify' => 'users#verify', as: :verify_user

  root 'speeches#index'
  get 'speeches/:id' => 'speeches#show', as: :speech
  post 'speeches/:id/share' => 'speeches#share', as: :share_speech
  get 'users/pending' => 'users#confirm_pending', as: :confirm_pending

  namespace :api do
    get "speeches" => 'speeches#index'
    post 'speeches' => 'speeches#create'
    get 'authors' => 'speeches#authors'
    get 'speeches/:id' => 'speeches#show'
  end
end

app/models/speech.rb
class Speech < ActiveRecord::Base

  include PgSearch

  validates :title, :author, :content, presence: true

  pg_search_scope :search_all,
                  :against => [
                    :title,
                    :author,
                    :content
                  ],
                  :using => {
                    :tsearch => {
                      :prefix => true,
                      :negation => true,
                      :dictionary => "english"
                    }
                  }
end

app/models/user.rb
class User < ActiveRecord::Base

  validates :email, presence: true
  has_secure_password
end

app/controllers/api/speeches_controller.rb
class Api::SpeechesController < ApplicationController

  protect_from_forgery with: :null_session

  def index
    search_text = params[:search]
    @speeches = Speech.all
    if search_text.present?
      @speeches = @speeches.search_all(params[:search])
    end
  end

  def authors
    render json: {authors: Speech.pluck(:author).uniq.sort }
  end

  def show
    @speech = Speech.find_by id: params[:id]
  end

  def create
    @speech = Speech.new params.require(:speech).permit(:author, :title, :content)
    if @speech.save
      render :show
    else
      render json: @speech.errors, status: 422
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action do
    @current_user = User.find_by id: session[:user_id]
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:email]
    password = params[:password]
    @user = User.find_by email: email
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def delete
    session.delete :user_id
    redirect_to root_path
  end
end

app/controllers/speeches_controller.rb
class SpeechesController < ApplicationController

  before_action do
    if @current_user.blank?
      redirect_to sign_in_path
    else
      redirect_to confirm_pending_path unless @current_user.confirmed?
    end
  end

  def index
    search_text = params[:search]
    @speeches = Speech.all
    if search_text.present?
      # @speeches = @speeches.where("title ILIKE ?", "%#{search_text}%")
      @speeches = @speeches.search_all(params[:search])
    end
  end

  def show
    @speech = Speech.find_by id: params[:id]
  end

  def share
    @speech = Speech.find_by id: params[:id]

    # Email this email via email to someone's email

    #mailer-name . action . deliver_now
    SpeechesMailer.share(@speech).deliver_now

    redirect_to root_path
  end
end

app/controllers/users_controller.rb
require 'securerandom'

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new params.require(:user).permit(:email, :password)
    @user.confirm_token = SecureRandom.hex
    if @user.save
      # Send a confirmation link to the user
      UserMailer.confirmation(@user).deliver_now
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def verify
    @user = User.find_by confirm_token: params[:confirm_token]
    if @user.present?
      @user.update confirmed: true, confirm_token: nil
      redirect_to root_path
    else
      render :confirm_pending
    end
  end

  def confirm_pending
  end
end

app/helpers/api/speeches_helper.rb
module Api::SpeechesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/speeches_helper.rb
module SpeechesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Speechy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <% if @current_user %>
      <%= link_to 'Sign Out', sign_out_path, method: :delete %>
    <% end %>
  </header>

<%= yield %>

</body>
</html>

app/views/speeches/index.html.erb
<p>Hi <%= @current_user.email %></p>

<%= form_tag root_path, method: :get do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end %>

<h1>Speeches <small><%= pluralize @speeches.count, 'result' %></small></h1>

<% @speeches.each do |speech| %>
  <h1><%= link_to speech.title, speech_path(id: speech.id) %> by <%= speech.author %></h1>
  <blockquote><%= highlight excerpt(speech.content, params[:search]), params[:search] %></blockquote>
<% end %>

app/views/speeches/show.html.erb
<h1><%= @speech.title %> by <%= @speech.author %></h1>

<%= link_to 'Share This Speech', share_speech_path(id: @speech.id), method: :post %>

<%= simple_format @speech.content %>

app/views/users/confirm_pending.html.erb
YO! Click that link we emailed you!

app/views/users/new.html.erb
<h1>Sign Up!</h1>

<% @user.errors.full_messages.each do |error| %>
  <li><%= error %></li>
<% end %>

<%= form_for @user do |f| %>
  <div class="">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="">
    <%= f.submit %>
  </div>
<% end %>